function scr_stringplay(_string){
	return(
	string(
			_string,
			"\n",
			"{",
			string(global.playtextlist[1]),
			string(global.playtextlist[2]),
			string(global.playtextlist[3]),
			global.fileread[0],
			global.fileread[1],
			global.fileread[2],
			global.fileread[global.level*2+4],
			global.fileread[global.level*2+3],
			global.judgelist[0],
			global.judgelist[1],
			global.judgelist[2],
			global.judgelist[3],
			string_format(fps,0,0),
			string(global.settings[17]),
			global.playtextlist[0],
			global.playtextlist[4],
			chr(global.pressext[0]),
			chr(global.pressext[1])
		)
	);
}