function scr_nibl2str(_rpnall){
	var _str="";
	var _num=0;
	for(_num=0;_num<array_length(_rpnall[0]);_num++){
		var _cal=[];
		for(var _i=0;_i<array_length(_rpnall[0][_num]);_i++){
			if(_rpnall[0][_num][_i]=="+"){
				if(typeof(_cal[array_length(_cal)-2])=="array"){
					_cal[array_length(_cal)-2]=
					_cal[array_length(_cal)-2][0]
					+_cal[array_length(_cal)-2][1]
					+_cal[array_length(_cal)-2][2];
				}
				if(typeof(_cal[array_length(_cal)-1])=="array"){
					_cal[array_length(_cal)-1]=
					_cal[array_length(_cal)-1][0]
					+_cal[array_length(_cal)-1][1]
					+_cal[array_length(_cal)-1][2];
				}
				_cal[array_length(_cal)-2]=
				[_cal[array_length(_cal)-2],"+",_cal[array_length(_cal)-1]];
				array_pop(_cal);
			}
			else if(_rpnall[0][_num][_i]=="-"){
				if(typeof(_cal[array_length(_cal)-2])=="array"){
					_cal[array_length(_cal)-2]=
					_cal[array_length(_cal)-2][0]
					+_cal[array_length(_cal)-2][1]
					+_cal[array_length(_cal)-2][2];
				}
				if(typeof(_cal[array_length(_cal)-1])=="array"){
					if(_cal[array_length(_cal)-1][1]=="+"||_cal[array_length(_cal)-1][1]=="-"){
					_cal[array_length(_cal)-1]=
					"("+_cal[array_length(_cal)-1][0]
					+_cal[array_length(_cal)-1][1]
					+_cal[array_length(_cal)-1][2]+")";
					}
					else{
					_cal[array_length(_cal)-1]=
					_cal[array_length(_cal)-1][0]
					+_cal[array_length(_cal)-1][1]
					+_cal[array_length(_cal)-1][2];
					}
				}
				_cal[array_length(_cal)-2]=
				[_cal[array_length(_cal)-2],"-",_cal[array_length(_cal)-1]];
				array_pop(_cal);
			}
			else if(_rpnall[0][_num][_i]=="*"){
				if(typeof(_cal[array_length(_cal)-2])=="array"){
					if(_cal[array_length(_cal)-2][1]=="+"||_cal[array_length(_cal)-2][1]=="-"){
						_cal[array_length(_cal)-2]=
						"("+_cal[array_length(_cal)-2][0]
						+_cal[array_length(_cal)-2][1]
						+_cal[array_length(_cal)-2][2]+")";
					}
					else{
						_cal[array_length(_cal)-2]=
						_cal[array_length(_cal)-2][0]
						+_cal[array_length(_cal)-2][1]
						+_cal[array_length(_cal)-2][2];
					}
				}
				if(typeof(_cal[array_length(_cal)-1])=="array"){
					if(_cal[array_length(_cal)-1][1]=="+"||_cal[array_length(_cal)-1][1]=="-"){
					_cal[array_length(_cal)-1]=
					"("+_cal[array_length(_cal)-1][0]
					+_cal[array_length(_cal)-1][1]
					+_cal[array_length(_cal)-1][2]+")";
					}
					else{
					_cal[array_length(_cal)-1]=
					_cal[array_length(_cal)-1][0]
					+_cal[array_length(_cal)-1][1]
					+_cal[array_length(_cal)-1][2];
					}
				}
				_cal[array_length(_cal)-2]=
				[_cal[array_length(_cal)-2],"*",_cal[array_length(_cal)-1]];
				array_pop(_cal);
			}
			else if(_rpnall[0][_num][_i]=="/"){
				if(typeof(_cal[array_length(_cal)-2])=="array"){
					if(_cal[array_length(_cal)-2][1]=="+"||_cal[array_length(_cal)-2][1]=="-"){
						_cal[array_length(_cal)-2]=
						"("+_cal[array_length(_cal)-2][0]
						+_cal[array_length(_cal)-2][1]
						+_cal[array_length(_cal)-2][2]+")";
					}
					else{
						_cal[array_length(_cal)-2]=
						_cal[array_length(_cal)-2][0]
						+_cal[array_length(_cal)-2][1]
						+_cal[array_length(_cal)-2][2];
					}
				}
				if(typeof(_cal[array_length(_cal)-1])=="array"){
					if(_cal[array_length(_cal)-1][1]=="+"||_cal[array_length(_cal)-1][1]=="-"
					||_cal[array_length(_cal)-1][1]=="*"||_cal[array_length(_cal)-1][1]=="/"){
					_cal[array_length(_cal)-1]=
					"("+_cal[array_length(_cal)-1][0]
					+_cal[array_length(_cal)-1][1]
					+_cal[array_length(_cal)-1][2]+")";
					}
					else{
					_cal[array_length(_cal)-1]=
					_cal[array_length(_cal)-1][0]
					+_cal[array_length(_cal)-1][1]
					+_cal[array_length(_cal)-1][2];
					}
				}
				_cal[array_length(_cal)-2]=
				[_cal[array_length(_cal)-2],"/",_cal[array_length(_cal)-1]];
				array_pop(_cal);
			}
			else if(_rpnall[0][_num][_i]=="^"){
				if(typeof(_cal[array_length(_cal)-2])=="array"){
					if(_cal[array_length(_cal)-2][1]=="+"||_cal[array_length(_cal)-2][1]=="-"
					||_cal[array_length(_cal)-2][1]=="*"||_cal[array_length(_cal)-2][1]=="/"
					||_cal[array_length(_cal)-2][1]=="^"){
						_cal[array_length(_cal)-2]=
						"("+_cal[array_length(_cal)-2][0]
						+_cal[array_length(_cal)-2][1]
						+_cal[array_length(_cal)-2][2]+")";
					}
					else{
						_cal[array_length(_cal)-2]=
						_cal[array_length(_cal)-2][0]
						+_cal[array_length(_cal)-2][1]
						+_cal[array_length(_cal)-2][2];
					}
				}
				if(typeof(_cal[array_length(_cal)-1])=="array"){
					if(_cal[array_length(_cal)-1][1]=="+"||_cal[array_length(_cal)-1][1]=="-"
					||_cal[array_length(_cal)-1][1]=="*"||_cal[array_length(_cal)-1][1]=="/"){
					_cal[array_length(_cal)-1]=
					"("+_cal[array_length(_cal)-1][0]
					+_cal[array_length(_cal)-1][1]
					+_cal[array_length(_cal)-1][2]+")";
					}
					else{
					_cal[array_length(_cal)-1]=
					_cal[array_length(_cal)-1][0]
					+_cal[array_length(_cal)-1][1]
					+_cal[array_length(_cal)-1][2];
					}
				}
				_cal[array_length(_cal)-2]=
				[_cal[array_length(_cal)-2],"^",_cal[array_length(_cal)-1]];
				array_pop(_cal);
			}
			else if(_rpnall[0][_num][_i]=="pow"){
				if(typeof(_cal[array_length(_cal)-2])=="array"){
					_cal[array_length(_cal)-2]=
					_cal[array_length(_cal)-2][0]
					+_cal[array_length(_cal)-2][1]
					+_cal[array_length(_cal)-2][2];
				}
				if(typeof(_cal[array_length(_cal)-1])=="array"){
					_cal[array_length(_cal)-1]=
					_cal[array_length(_cal)-1][0]
					+_cal[array_length(_cal)-1][1]
					+_cal[array_length(_cal)-1][2];
				}
				_cal[array_length(_cal)-2]=
				"pow("+_cal[array_length(_cal)-2]+","+_cal[array_length(_cal)-1]+")";
				array_pop(_cal);
			}
			else if(_rpnall[0][_num][_i]=="abs"){
				if(typeof(_cal[array_length(_cal)-1])=="array"){
					_cal[array_length(_cal)-1]=
					_cal[array_length(_cal)-1][0]
					+_cal[array_length(_cal)-1][1]
					+_cal[array_length(_cal)-1][2];
				}
				_cal[array_length(_cal)-1]=
				"abs("+_cal[array_length(_cal)-1]+")";
			}
			else if(_rpnall[0][_num][_i]=="sin"){
				if(typeof(_cal[array_length(_cal)-1])=="array"){
					_cal[array_length(_cal)-1]=
					_cal[array_length(_cal)-1][0]
					+_cal[array_length(_cal)-1][1]
					+_cal[array_length(_cal)-1][2];
				}
				_cal[array_length(_cal)-1]=
				"sin("+_cal[array_length(_cal)-1]+")";
			}
			else if(_rpnall[0][_num][_i]=="cos"){
				if(typeof(_cal[array_length(_cal)-1])=="array"){
					_cal[array_length(_cal)-1]=
					_cal[array_length(_cal)-1][0]
					+_cal[array_length(_cal)-1][1]
					+_cal[array_length(_cal)-1][2];
				}
				_cal[array_length(_cal)-1]=
				"cos("+_cal[array_length(_cal)-1]+")";
			}
			else if(_rpnall[0][_num][_i]=="x") {
				array_push(_cal,"x");
			}
			else if(_rpnall[0][_num][_i]=="spd") {
				array_push(_cal,"spd");
			}
			else if(_rpnall[0][_num][_i]=="ly") {
				array_push(_cal,"ly");
			}
			else if(_rpnall[0][_num][_i]=="lx1") {
				array_push(_cal,"lx1");
			}
			else if(_rpnall[0][_num][_i]=="lx2") {
				array_push(_cal,"lx2");
			}
			else if(_rpnall[0][_num][_i]=="3.14159") {
				array_push(_cal,"p");
			}
			else {
				array_push(_cal,scr_floatostring(_rpnall[0][_num][_i]));
			}
		}
		if(typeof(_cal[0])=="array"){
			_cal[0]=
			_cal[0][0]
			+_cal[0][1]
			+_cal[0][2];
		}
		_str+=_cal[0];
		if(_num<array_length(_rpnall[1])){
		_str+=";";
		_str+=scr_floatostring(_rpnall[1][_num]);
		_str+=";";
		}
	}
	return(_str);
}